version: "3.10"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - internal_network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - internal_network

networks:
  internal_network:
