version: "3.10"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"  # Expose RabbitMQ management interface port
    tty: true
    command: bash -c "rabbitmq-server;"
    networks:
      - back

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - back

  app:
    build: .
    depends_on:
      - rabbitmq
      - redis
    networks:
      - back

networks:
  back: